# Generated by Django 4.2 on 2023-04-11 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0002_notice_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
