# Generated by Django 4.2.2 on 2023-06-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_notice_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
