# Generated by Django 4.2.2 on 2023-06-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0007_alter_notice_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.TextField(blank=True)),
            ],
        ),
    ]
